version: '3.9'

services:
  stable-diffusion-dev:
    build:
      context: ../../..
      dockerfile: docker/huggingface/stable_diffusion/Dockerfile
    environment:
      GIT_PYTHON_REFRESH: "quiet"
    volumes:
      - ../../..:/workspace
    command: ["tail", "-f", "/dev/null"]

  stable-diffusion:
    build:
      context: ../../..
      dockerfile: docker/huggingface/stable_diffusion/Dockerfile
    environment:
      GIT_PYTHON_REFRESH: "quiet"

