mode: test

defaults:
  - dataset: MVTecDataset
  - network: Unet
  - loss: CrossEntropyLoss
  - trainer: UnetTrainer
  - _self_

trainer:
  UnetTrainer:
    device: cuda:0
    pretrained_checkpoint_path: /workspace/outputs/checkpoints/epoch_3.pt
    is_export_tensorrt: true
